name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: 检出项目代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 安装 vcpkg
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    # Step 3: 安装 ViGEmClient
    - name: Install ViGEmClient dependencies
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}"

    # Step 4: 使用 CMake 构建 DLL
    - name: Build ViGEmClient DLL
      run: |
        mkdir build
        cd build
        cmake ../overlay-ports/vigemclient -A x64 -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build . --config Release

    # Step 5: 上传构建生成的 DLL 文件
    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLL
        path: build/Release/*.dll
