name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install ViGEmClient dependencies
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}"

    - name: Build ViGEmClient DLL
      run: |
        mkdir build
        cd build
        cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake
        cmake --build . --config Release

    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLL
        path: build/Release/*.dll
