name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Remove existing overlay-ports directory
      run: |
        if (Test-Path overlay-ports) { Remove-Item -Recurse -Force overlay-ports }

    - name: Clone ViGEmClient.vcpkg
      run: |
        git clone https://github.com/ViGEm/ViGEmClient.vcpkg.git overlay-ports

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install ViGEmClient using vcpkg
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}/overlay-ports"

    - name: Debug package directories
      run: |
        ls -Recurse vcpkg/packages/vigemclient_x64-windows || echo "No x64 package directory found."
        ls -Recurse vcpkg/packages/vigemclient_x86-windows || echo "No x86 package directory found."

    - name: Upload DLLs from packages
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLLs
        path: |
          vcpkg/packages/vigemclient_x64-windows/**/*.dll
          vcpkg/packages/vigemclient_x86-windows/**/*.dll
