name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3

    - name: Remove existing overlay-ports directory
      run: |
        if (Test-Path overlay-ports) { Remove-Item -Recurse -Force overlay-ports }

    - name: Clone ViGEmClient.vcpkg
      run: |
        git clone https://github.com/ViGEm/ViGEmClient.vcpkg.git overlay-ports

    - name: Validate overlay-ports files
      run: |
        ls overlay-ports || echo "overlay-ports directory missing."
        cat overlay-ports/CONTROL || echo "CONTROL file missing."
        cat overlay-ports/portfile.cmake || echo "portfile.cmake file missing."

    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Capture vcpkg install output
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}/overlay-ports" | tee vcpkg-install.log
        cat vcpkg-install.log || echo "No output captured from vcpkg install."

    - name: Debug buildtrees directory
      run: |
        ls -Recurse buildtrees || echo "No files found in buildtrees."

    - name: Upload vcpkg install log
      uses: actions/upload-artifact@v3
      with:
        name: vcpkg-install-log
        path: vcpkg-install.log

    - name: Upload buildtrees logs
      uses: actions/upload-artifact@v3
      with:
        name: buildtrees-logs
        path: buildtrees/**/*.log
