name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the main repository
    - name: Checkout main repository
      uses: actions/checkout@v3

    # Step 2: Remove existing overlay-ports directory
    - name: Remove existing overlay-ports directory
      run: |
        if (Test-Path overlay-ports) { Remove-Item -Recurse -Force overlay-ports }

    # Step 3: Clone the ViGEmClient.vcpkg repository (overlay-ports)
    - name: Clone ViGEmClient.vcpkg
      run: |
        git clone https://github.com/ViGEm/ViGEmClient.vcpkg.git overlay-ports

    # Step 4: Clone and bootstrap vcpkg
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    # Step 5: Install ViGEmClient using vcpkg with overlay-ports
    - name: Install ViGEmClient
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}/overlay-ports"

    # Step 6: Debug vcpkg logs
    - name: Debug vcpkg logs
      run: |
        cat buildtrees/vigemclient/install-x86-windows-dbg-out.log || echo "No x86 debug log found."
        cat buildtrees/vigemclient/install-x64-windows-dbg-out.log || echo "No x64 debug log found."
        cat buildtrees/vigemclient/build-x86-windows-dbg-out.log || echo "No x86 build log found."
        cat buildtrees/vigemclient/build-x64-windows-dbg-out.log || echo "No x64 build log found."

    # Step 7: Verify overlay-ports directory
    - name: Verify overlay-ports directory
      run: |
        ls overlay-ports/vigemclient || echo "No vigemclient port found in overlay-ports."

    # Step 8: List all files in vcpkg_installed
    - name: List all files in vcpkg_installed
      run: |
        ls -Recurse vcpkg_installed || echo "No files found in vcpkg_installed."

    # Step 9: Upload DLL artifacts
    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLL
        path: |
          vcpkg_installed/x86-windows/bin/*.dll
          vcpkg_installed/x64-windows/bin/*.dll
