name: Build ViGEmClient DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Clone and bootstrap vcpkg
    - name: Setup vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    # Step 3: Verify overlay-ports directory
    - name: Verify overlay-ports directory
      run: |
        ls overlay-ports/vigemclient

    # Step 4: Clean vcpkg cache
    - name: Clean vcpkg cache
      run: |
        .\vcpkg\vcpkg.exe remove --outdated

    # Step 5: Install ViGEmClient using vcpkg with overlay-ports
    - name: Install ViGEmClient
      run: |
        .\vcpkg\vcpkg.exe install vigemclient:x86-windows vigemclient:x64-windows --overlay-ports="${{ github.workspace }}/overlay-ports"

    # Step 6: Upload the generated DLL files
    - name: Upload DLL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ViGEmClient-DLL
        path: |
          vcpkg_installed/x86-windows/bin/*.dll
          vcpkg_installed/x64-windows/bin/*.dll
